# Generated by Django 2.1.5 on 2019-01-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_img',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
