# Generated by Django 2.1.5 on 2019-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviepoll', '0002_choice_choice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_description',
            field=models.CharField(blank=True, default=False, max_length=500),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_duration',
            field=models.IntegerField(blank=True, default=False, max_length=400),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_genre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_imdb',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_img',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images'),
        ),
    ]
